#!/bin/sh
### BEGIN INIT INFO
# Provides:          data-collector
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Data collector daemon
# Description:       Collects sensor data and sends to web server
### END INIT INFO

DAEMON=/usr/bin/data-collector
PIDFILE=/var/run/data-collector.pid
NAME=data-collector

case "$1" in
    start)
        echo "Starting $NAME..."
        start-stop-daemon --start --quiet --background \
            --make-pidfile --pidfile $PIDFILE \
            --exec $DAEMON
        echo "Done."
        ;;
    stop)
        echo "Stopping $NAME..."
        start-stop-daemon --stop --quiet --pidfile $PIDFILE
        rm -f $PIDFILE
        echo "Done."
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if [ -f $PIDFILE ]; then
            PID=$(cat $PIDFILE)
            if ps -p $PID > /dev/null 2>&1; then
                echo "$NAME is running (PID: $PID)"
                exit 0
            else
                echo "$NAME is not running but PID file exists"
                exit 1
            fi
        else
            echo "$NAME is not running"
            exit 3
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0