#!/bin/sh
### BEGIN INIT INFO
# Provides:          bmp180-client
# Required-Start:    $remote_fs $syslog data-collector
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: BMP180 I2C sensor client
# Description:       Reads temperature and pressure from the BMP180 sensor
#                    and forwards values to the data-collector daemon.
### END INIT INFO

DAEMON=/usr/bin/bmp180-client
NAME=bmp180-client
PIDFILE=/var/run/bmp180-client.pid

case "$1" in
    start)
        echo "Starting $NAME"
        start-stop-daemon --start --background \
            --make-pidfile --pidfile $PIDFILE \
            --exec $DAEMON
        ;;
    stop)
        echo "Stopping $NAME"
        start-stop-daemon --stop --pidfile $PIDFILE
        rm -f $PIDFILE
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if [ -f $PIDFILE ] && kill -0 "$(cat $PIDFILE)" 2>/dev/null; then
            echo "$NAME is running (pid $(cat $PIDFILE))"
        else
            echo "$NAME is not running"
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0